//
//  AppConstants.h
//  KanKan
//
//  Created by Zhaohui Xing on 2013-05-15.
//  Copyright (c) 2013 Zhaohui Xing. All rights reserved.
//

#ifndef KanKan_AppConstants_h
#define KanKan_AppConstants_h

#include "GUIBasicConstant.h"

#define	GUIID_SEARCHMENU_ID                                       (GUIID_BASIC_IDLAST + 1)
#define	GUIID_POSTMENU_ID                                         (GUIID_BASIC_IDLAST + 2)
#define	GUIID_SETTINGMENU_ID                                      (GUIID_BASIC_IDLAST + 3)

#define GUIID_SEARCHMENU_ROOTMENU_ID                                (GUIID_BASIC_IDLAST + 4)
#define GUIID_SEARCHMENU_ITEM_TRAFFIC_ID                            (GUIID_BASIC_IDLAST + 5)
#define GUIID_SEARCHMENU_ITEM_MARKSPOT_ID                                         (GUIID_BASIC_IDLAST + 6)


#define GUIID_SEARCHMENU_TRAFFICMENU_ID                                         (GUIID_BASIC_IDLAST + 7)
#define GUIID_SEARCHMENU_TRAFFICMENU_ITEM_PUBLICTRANSIT_ID                      (GUIID_BASIC_IDLAST + 8)
#define GUIID_SEARCHMENU_TRAFFICMENU_ITEM_DRIVINGCONDITION_ID                   (GUIID_BASIC_IDLAST + 9)
#define GUIID_SEARCHMENU_TRAFFICMENU_ITEM_ALL_ID                                (GUIID_BASIC_IDLAST + 10)

#define GUIID_SEARCHMENU_TRAFFICMENU_PUBLICTRANSITMENU_ID                                      (GUIID_BASIC_IDLAST + 11)
#define GUIID_SEARCHMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_DELAY_ID                           (GUIID_BASIC_IDLAST + 12)
#define GUIID_SEARCHMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_PASSENGERSTUCK_ID                  (GUIID_BASIC_IDLAST + 13)
#define GUIID_SEARCHMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_ALL_ID                             (GUIID_BASIC_IDLAST + 14)

#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ID                                            (GUIID_BASIC_IDLAST + 15)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_JAM_ID                                   (GUIID_BASIC_IDLAST + 16)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_CRASH_ID                                 (GUIID_BASIC_IDLAST + 17)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_POLICE_ID                                (GUIID_BASIC_IDLAST + 18)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_CONSTRUCTION_ID                          (GUIID_BASIC_IDLAST + 19)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_ROADCLOSURE_ID                           (GUIID_BASIC_IDLAST + 20)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_BROKENTRAFFICLIGHT_ID                    (GUIID_BASIC_IDLAST + 23)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_STALLEDCAR_ID                                  (GUIID_BASIC_IDLAST + 24)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_FOG_ID                                         (GUIID_BASIC_IDLAST + 25)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_DANGEROUSCONDITION_ID                          (GUIID_BASIC_IDLAST + 26)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_RAIN_ID                          (GUIID_BASIC_IDLAST + 27)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_ICE_ID                          (GUIID_BASIC_IDLAST + 28)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_WIND_ID                          (GUIID_BASIC_IDLAST + 29)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_LANECLOSURE_ID                          (GUIID_BASIC_IDLAST + 30)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_SLIPROADCLOSURE_ID                          (GUIID_BASIC_IDLAST + 31)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_DETOUR_ID                          (GUIID_BASIC_IDLAST + 32)
#define GUIID_SEARCHMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_ALL_ID                                   (GUIID_BASIC_IDLAST + 33)


#define GUIID_SEARCHMENU_SHOWSPOTMENU_ID                                           (GUIID_BASIC_IDLAST + 34)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_ITEM_TRAFFICSPOTMENU_ID                      (GUIID_BASIC_IDLAST + 35)

#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ID                                  (GUIID_BASIC_IDLAST + 36)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_SPEEDLIMIT_ID                  (GUIID_BASIC_IDLAST + 37)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_GASSTATION_ID                  (GUIID_BASIC_IDLAST + 38)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_PARKINGGROUND_ID               (GUIID_BASIC_IDLAST + 39)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_ALL_ID                         (GUIID_BASIC_IDLAST + 40)

#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ID                  (GUIID_BASIC_IDLAST + 41)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_PHOTORADAR_ID  (GUIID_BASIC_IDLAST + 42)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_SCHOOLZONE_ID  (GUIID_BASIC_IDLAST + 43)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_PLAYGROUND_ID  (GUIID_BASIC_IDLAST + 44)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_ALL_ID  (GUIID_BASIC_IDLAST + 45)

#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ID                          (GUIID_BASIC_IDLAST + 46)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_REDLIGHTCAMERA_ID      (GUIID_BASIC_IDLAST + 47)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_SPEEDCAMERA_ID         (GUIID_BASIC_IDLAST + 48)
#define GUIID_SEARCHMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_ALL_ID                 (GUIID_BASIC_IDLAST + 49)



#define GUIID_POSTMENU_ROOTMENU_ID                                              (GUIID_BASIC_IDLAST + 50)
#define GUIID_POSTMENU_ITEM_TRAFFIC_ID                                          (GUIID_BASIC_IDLAST + 51)
#define GUIID_POSTMENU_ITEM_MARKSPOT_ID                                         (GUIID_BASIC_IDLAST + 52)


#define GUIID_POSTMENU_TRAFFICMENU_ID                                           (GUIID_BASIC_IDLAST + 53)
#define GUIID_POSTMENU_TRAFFICMENU_ITEM_PUBLICTRANSIT_ID                        (GUIID_BASIC_IDLAST + 54)
#define GUIID_POSTMENU_TRAFFICMENU_ITEM_DRIVINGCONDITION_ID                     (GUIID_BASIC_IDLAST + 55)

#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ID                                         (GUIID_BASIC_IDLAST + 56)
//#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_DELAY_ID                              (GUIID_BASIC_IDLAST + 57)
#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_BUS_DELAY_ID                          (GUIID_BASIC_IDLAST + 57)
#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_TRAIN_DELAY_ID                        (GUIID_BASIC_IDLAST + 58)
#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_FLIGHT_DELAY_ID                       (GUIID_BASIC_IDLAST + 59)
#define GUIID_POSTMENU_TRAFFICMENU_PUBLICTRANSITMENU_ITEM_PASSENGERSTUCK_ID                     (GUIID_BASIC_IDLAST + 60)

#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ID                                         (GUIID_BASIC_IDLAST + 61)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_JAM_ID                               (GUIID_BASIC_IDLAST + 62)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_CRASH_ID                             (GUIID_BASIC_IDLAST + 63)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_POLICE_ID                             (GUIID_BASIC_IDLAST + 64)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_CONSTRUCTION_ID                             (GUIID_BASIC_IDLAST + 65)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_ROADCLOSURE_ID                             (GUIID_BASIC_IDLAST + 66)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_BROKENTRAFFICLIGHT_ID                    (GUIID_BASIC_IDLAST + 67)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_STALLEDCAR_ID                                  (GUIID_BASIC_IDLAST + 68)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_FOG_ID                                         (GUIID_BASIC_IDLAST + 69)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_DANGEROUSCONDITION_ID                          (GUIID_BASIC_IDLAST + 70)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_RAIN_ID                          (GUIID_BASIC_IDLAST + 71)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_ICE_ID                          (GUIID_BASIC_IDLAST + 72)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_WIND_ID                          (GUIID_BASIC_IDLAST + 73)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_LANECLOSURE_ID                          (GUIID_BASIC_IDLAST + 74)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_SLIPROADCLOSURE_ID                          (GUIID_BASIC_IDLAST + 75)
#define GUIID_POSTMENU_TRAFFICMENU_DRIVINGCONDITIONMENU_ITEM_DETOUR_ID                          (GUIID_BASIC_IDLAST + 76)


#define GUIID_POSTMENU_MARKSPOTMENU_ITEM_TRAFFICSPOT_ID                        (GUIID_BASIC_IDLAST + 77)
#define GUIID_POSTMENU_MARKSPOTMENU_ITEM_LOCALSPOT_ID                          (GUIID_BASIC_IDLAST + 78)

#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ID                                         (GUIID_BASIC_IDLAST + 79)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ITEM_PHOTORADAR_ID                         (GUIID_BASIC_IDLAST + 80)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ITEM_SCHOOLZONE_ID                         (GUIID_BASIC_IDLAST + 81)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ITEM_PLAYGROUND_ID                         (GUIID_BASIC_IDLAST + 82)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ITEM_PARKINGGROUND_ID                      (GUIID_BASIC_IDLAST + 83)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_ITEM_GASSTATION_ID                         (GUIID_BASIC_IDLAST + 84)

#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_PHOTORADARMENU_ID                          (GUIID_BASIC_IDLAST + 85)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_PHOTORADARMENU_ITEM_REDLIGHTCAMERA_ID      (GUIID_BASIC_IDLAST + 86)
#define GUIID_POSTMENU_MARKSPOTMENU_TRAFFICSPOTMENU_PHOTORADARMENU_ITEM_SPEEDCAMERA_ID         (GUIID_BASIC_IDLAST + 87)


#define GUIID_SETTINGMENU_ROOTMENU_ID                                  (GUIID_BASIC_IDLAST + 88)
#define GUIID_SETTINGMENU_ITEM_MAPTYPE_ID                               (GUIID_BASIC_IDLAST + 89)
#define GUIID_SETTINGMENU_ITEM_CONFIGURATION_ID                        (GUIID_BASIC_IDLAST + 90)

#define GUIID_SETTINGMENU_ITEM_RELOAD_ID                                            (GUIID_BASIC_IDLAST + 91)
#define GUIID_SETTINGMENU_ITEM_CLEARMAP_ID                                            (GUIID_BASIC_IDLAST + 92)
#define GUIID_SETTINGMENU_ITEM_SHOWMYLOCATION_ID                                            (GUIID_BASIC_IDLAST + 93)

#define GUIID_SETTINGMENU_CONFIGURATIONMENU_ID                                          (GUIID_BASIC_IDLAST + 94)
#define GUIID_SETTINGMENU_CONFIGURATIONMENU_ITEM_QUERYCONFIGURATION_ID                        (GUIID_BASIC_IDLAST + 95)
#define GUIID_SETTINGMENU_CONFIGURATIONMENU_ITEM_USERCONFIGURATION_ID                      (GUIID_BASIC_IDLAST + 96)

#define GUIID_SETTINGMENU_MAPTYPEMENU_ID                                            (GUIID_BASIC_IDLAST + 97)
#define GUIID_SETTINGMENU_MAPTYPEMENU_ITEM_MAPSTANDARD_ID                           (GUIID_BASIC_IDLAST + 98)
#define GUIID_SETTINGMENU_MAPTYPEMENU_ITEM_MAPHYBIRD_ID                             (GUIID_BASIC_IDLAST + 99)
#define GUIID_SETTINGMENU_MAPTYPEMENU_ITEM_MAPSATELLITE_ID                          (GUIID_BASIC_IDLAST + 100)
#define GUIID_SETTINGMENU_MAPTYPEMENU_ITEM_SPOTS_ID                                 (GUIID_BASIC_IDLAST + 101)


#define GUIID_SETTINGMENU_ITEM_OPENPRIVACYVIEW_ID                                           (GUIID_BASIC_IDLAST + 102)
#define GUIID_SETTINGMENU_ITEM_OPENTERMSOFUSEVIEW_ID                                        (GUIID_BASIC_IDLAST + 103)

#define GUIID_SETTINGMENU_SHOWSPOTMENU_ID                                           (GUIID_BASIC_IDLAST + 104)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_ITEM_TRAFFICSPOTMENU_ID                      (GUIID_BASIC_IDLAST + 105)

#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ID                                  (GUIID_BASIC_IDLAST + 106)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_SPEEDLIMIT_ID                  (GUIID_BASIC_IDLAST + 107)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_GASSTATION_ID                  (GUIID_BASIC_IDLAST + 108)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_PARKINGGROUND_ID               (GUIID_BASIC_IDLAST + 109)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_ITEM_ALL_ID                         (GUIID_BASIC_IDLAST + 110)

#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ID                  (GUIID_BASIC_IDLAST + 111)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_PHOTORADAR_ID  (GUIID_BASIC_IDLAST + 112)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_SCHOOLZONE_ID  (GUIID_BASIC_IDLAST + 113)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_PLAYGROUND_ID  (GUIID_BASIC_IDLAST + 114)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_ITEM_ALL_ID  (GUIID_BASIC_IDLAST + 115)

#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ID                          (GUIID_BASIC_IDLAST + 116)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_REDLIGHTCAMERA_ID      (GUIID_BASIC_IDLAST + 117)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_SPEEDCAMERA_ID         (GUIID_BASIC_IDLAST + 118)
#define GUIID_SETTINGMENU_SHOWSPOTMENU_TRAFFICSPOTMENU_SPEEDLIMITMENU_PHOTORADARMENU_ITEM_ALL_ID                 (GUIID_BASIC_IDLAST + 119)

#define GUIID_SETTINGMENU_ITEM_TWITTERSETTING_ID                                            (GUIID_BASIC_IDLAST + 120)

#define GUIID_SETTINGMENU_CLEARMAPMENU_ID                                                   (GUIID_BASIC_IDLAST + 121)
#define GUIID_SETTINGMENU_CLEARMAPMENU_ITEM_TRAFFIC_ID                                      (GUIID_BASIC_IDLAST + 122)
#define GUIID_SETTINGMENU_CLEARMAPMENU_ITEM_SPOT_ID                                         (GUIID_BASIC_IDLAST + 123)
#define GUIID_SETTINGMENU_CLEARMAPMENU_ITEM_ALL_ID                                          (GUIID_BASIC_IDLAST + 124)


#define TEST_TWITTER_GRANTACCESS_ID                 (GUIID_BASIC_IDLAST + 125)
#define TEST_TWITTER_ACCOUNTLIST_ID                 (GUIID_BASIC_IDLAST + 126)
#define TEST_TWITTER_CHECKUSERACCOUNT_ID            (GUIID_BASIC_IDLAST + 127)
#define TEST_TWITTER_CHECKSYSTEMACCOUNT_ID          (GUIID_BASIC_IDLAST + 128)
#define TEST_TWITTER_ADDSYSTEMACCOUNT_ID          (GUIID_BASIC_IDLAST + 129)
#define TEST_TWITTER_DELETESYSTEMACCOUNT_ID          (GUIID_BASIC_IDLAST + 130)
#define TEST_TWITTER_SEARCH_ID                      (GUIID_BASIC_IDLAST + 131)


#define GUIID_POSTMENU_ITEM_TAXISHARING_ID                                                  (GUIID_BASIC_IDLAST + 132)
#define GUIID_POSTMENU_TAXISHAREMENU_TAXISHAREMENU_ID                                       (GUIID_BASIC_IDLAST + 133)
#define GUIID_POSTMENU_TAXISHAREMENU_TAXISHAREMENU_ITEM_DRIVER_ID                           (GUIID_BASIC_IDLAST + 134)
#define GUIID_POSTMENU_TAXISHAREMENU_TAXISHAREMENU_ITEM_PASSENGER_ID                        (GUIID_BASIC_IDLAST + 135)

#define GUIID_SEARCHMENU_ITEM_TAXISHARING_ID                                         (GUIID_BASIC_IDLAST + 136)
#define GUIID_SEARCHMENU_TAXISHAREMENU_TAXISHAREMENU_ID                              (GUIID_BASIC_IDLAST + 137)
#define GUIID_SEARCHMENU_TAXISHAREMENU_TAXISHAREMENU_ITEM_DRIVER_ID                  (GUIID_BASIC_IDLAST + 138)
#define GUIID_SEARCHMENU_TAXISHAREMENU_TAXISHAREMENU_ITEM_PASSENGER_ID               (GUIID_BASIC_IDLAST + 139)
#define GUIID_SEARCHMENU_TAXISHAREMENU_TAXISHAREMENU_ITEM_ALL_ID                     (GUIID_BASIC_IDLAST + 140)


#define GUIID_SETTINGMENU_CLEARMAPMENU_ITEM_TAXI_ID                                             (GUIID_BASIC_IDLAST + 141)
#define GUIID_SETTINGMENU_CLEARMAPMENU_CLEARTAXIMENU_ID                                         (GUIID_BASIC_IDLAST + 142)
#define GUIID_SETTINGMENU_CLEARMAPMENU_CLEARTAXIMENU_ITEM_TAXIDRIVER_ID                         (GUIID_BASIC_IDLAST + 143)
#define GUIID_SETTINGMENU_CLEARMAPMENU_CLEARTAXIMENU_ITEM_TAXIPASSENGER_ID                      (GUIID_BASIC_IDLAST + 144)
#define GUIID_SETTINGMENU_CLEARMAPMENU_CLEARTAXIMENU_ITEM_ALL_ID                                (GUIID_BASIC_IDLAST + 145)

#endif
