/*
 *  ApplicationResource.h
 *  ChuiNiuLite
 *
 *  Created by Zhaohui Xing on 11-03-04.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */
#import "ApplicationConfigure.h"
#import "GUIBasicConstant.h"

#define	 PRODUCTID_DEFAULT					APPLICATION_PRODUCT_FLYINGCOW		


#define	 GUIID_DEFAULT						GUIID_BASIC_IDLAST
#define	 GUIID_INFOBUTTON					(GUIID_DEFAULT+1)
#define	 GUIID_PLAYBUTTON					(GUIID_DEFAULT+2)
#define	 GUIID_CONFIGUREBUTTON				(GUIID_DEFAULT+3)
#define	 GUIID_SCOREBUTTON					(GUIID_DEFAULT+4)
#define	 GUIID_POSTBUTTON					(GUIID_DEFAULT+5)
#define	 GUIID_SOUNDBUTTON                  (GUIID_DEFAULT+6)

#define	 GUIID_EVENT_GAMESTATECHANGE		(GUIID_DEFAULT+7)
#define	 GUIID_EVENT_OPENSCOREVIEW			(GUIID_DEFAULT+8)
#define	 GUIID_EVENT_OPENREDEEMVIEW			(GUIID_DEFAULT+9)
#define	 GUIID_EVENT_OPENCONFIGUREVIEW		(GUIID_DEFAULT+10)
#define	 GUIID_EVENT_OPENSHAREVIEW			(GUIID_DEFAULT+11)
#define	 GUIID_EVENT_WIZARDFINISHED			(GUIID_DEFAULT+12)

#define	 GUIID_EVENT_OFFLINE_POPUPMENU_ME	(GUIID_DEFAULT+13)
#define	 GUIID_EVENT_OFFLINE_POPUPMENU_PLAYER1	(GUIID_DEFAULT+14)
#define	 GUIID_EVENT_OFFLINE_POPUPMENU_PLAYER2	(GUIID_DEFAULT+15)
#define	 GUIID_EVENT_OFFLINE_POPUPMENU_PLAYER3	(GUIID_DEFAULT+16)

#define	 GUIID_EVENT_OFFLINE_POPUP_ME_CHIP	(GUIID_DEFAULT+17)
#define	 GUIID_EVENT_OFFLINE_POPUP_ME_EARN	(GUIID_DEFAULT+18)
#define	 GUIID_EVENT_OFFLINE_POPUP_ME_TRANSACTION	(GUIID_DEFAULT+19)

#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER1_CHIP	(GUIID_DEFAULT+20)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER1_EARN	(GUIID_DEFAULT+21)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER1_TRANSACTION	(GUIID_DEFAULT+22)

#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER2_CHIP	(GUIID_DEFAULT+23)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER2_EARN	(GUIID_DEFAULT+24)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER2_TRANSACTION	(GUIID_DEFAULT+25)

#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER3_CHIP	(GUIID_DEFAULT+26)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER3_EARN	(GUIID_DEFAULT+27)
#define	 GUIID_EVENT_OFFLINE_POPUP_PLAYER3_TRANSACTION	(GUIID_DEFAULT+28)

#define	 GUIID_FRIENDBUTTON                 	(GUIID_DEFAULT+29)

#define	 GUIID_EVENT_ONLINE_SHUTDOWN_GAMESECTION	(GUIID_DEFAULT+30)

#define	 GUIID_EVENT_ONLINE_GAMEEQUEST_DONE         (GUIID_DEFAULT+31)


#define	 GUIID_EVENT_ONLINE_POPUPMENU_CHIP              (GUIID_DEFAULT+32)
#define	 GUIID_EVENT_ONLINE_POPUPMENU_EARN              (GUIID_DEFAULT+33)
#define	 GUIID_EVENT_ONLINE_POPUPMENU_TRANSACTION       (GUIID_DEFAULT+34)
#define	 GUIID_EVENT_ONLINE_POPUPMENU_MESSAGE           (GUIID_DEFAULT+35)
#define	 GUIID_EVENT_ONLINE_POPUPMENU_LOCATION          (GUIID_DEFAULT+36)

#define	 GUIID_EVENT_PURCHASECHIPS                      (GUIID_DEFAULT+37)

#define	 GUIID_AWSCONFIGUREBUTTON				(GUIID_DEFAULT+38)

#define  GUIID_EVENT_ONLINESTATUSBUTTON         (GUIID_DEFAULT+39)

#define  GUIID_EVENT_ENABLEADBANNERVIEW         (GUIID_DEFAULT+40)
#define  GUIID_EVENT_PURCHASEFAILED             (GUIID_DEFAULT+41)


#define PLAYERUI_CANCEL                   0
#define PLAYERUI_SENDINVITATION           1
#define PLAYERUI_BUYIT                    2

