/*
 *  ApplicationResource.h
 *  ChuiNiuLite
 *
 *  Created by Zhaohui Xing on 11-03-04.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */
#import "ApplicationConfigure.h"
#import "GUIBasicConstant.h"

#define	 PRODUCTID_DEFAULT					APPLICATION_PRODUCT_FLYINGCOW		


#define	 GUIID_DEFAULT						GUIID_BASIC_IDLAST
#define	 GUIID_INFOBUTTON					(GUIID_DEFAULT+1)
#define	 GUIID_PLAYBUTTON					(GUIID_DEFAULT+2)
#define	 GUIID_SOUNDBUTTON					(GUIID_DEFAULT+3)
#define	 GUIID_BKGNDBUTTON					(GUIID_DEFAULT+4)
#define	 GUIID_LEVELBUTTON					(GUIID_DEFAULT+5)
#define	 GUIID_SCOREBUTTON					(GUIID_DEFAULT+6)
#define	 GUIID_POSTBUTTON					(GUIID_DEFAULT+7)
#define	 GUIID_CLOCKBUTTON					(GUIID_DEFAULT+8)
#define	 GUIID_EVENT_OPENCONFIGUREVIEW		(GUIID_DEFAULT+9)
#define	 GUIID_EVENT_OPENSCOREVIEW			(GUIID_DEFAULT+10)
#define	 GUIID_EVENT_OPENSHAREVIEW			(GUIID_DEFAULT+11)
#define	 GUIID_EVENT_THUNDERTHENEBUTTON		(GUIID_DEFAULT+12)
#define	 GUIID_EVENT_FACEBOOKSHARELAST		(GUIID_DEFAULT+13)
#define	 GUIID_EVENT_FACEBOOKSHAREALL		(GUIID_DEFAULT+14)
#define	 GUIID_EVENT_RENRENSHARELAST        (GUIID_DEFAULT+15)
#define	 GUIID_EVENT_RENRENSHAREALL         (GUIID_DEFAULT+16)
#define	 GUIID_EVENT_QQSHARELAST            (GUIID_DEFAULT+17)
#define	 GUIID_EVENT_QQSHAREALL             (GUIID_DEFAULT+18)
#define	 GUIID_EVENT_SINASHARELAST          (GUIID_DEFAULT+19)
#define	 GUIID_EVENT_SINASHAREALL           (GUIID_DEFAULT+20)
#define	 GUIID_EVENT_QQLOGINFAILED          (GUIID_DEFAULT+21)
#define	 GUIID_EVENT_QQLOGINSUCCEED         (GUIID_DEFAULT+22)

#define	 GUIID_PURCHASEBUTTON				(GUIID_DEFAULT+23)
#define	 GUIID_EVENT_PURCHASE				(GUIID_DEFAULT+24)

#define GUIID_EVENT_TWITTERSHARELAST		(GUIID_DEFAULT+25)
#define	GUIID_EVENT_TWITTERSHAREALL         (GUIID_DEFAULT+26)

#define	GUIID_EVENT_RESETGAME               (GUIID_DEFAULT+27)
#define	GUIID_EVENT_POSTWINMESSAGE          (GUIID_DEFAULT+28)
#define	GUIID_EVENT_POSTLOSTMESSAGE         (GUIID_DEFAULT+29)

#define	GUIID_FRIENDBUTTON                  (GUIID_DEFAULT+30)
#define	GUIID_OPENFRIENDVIEW                (GUIID_DEFAULT+31)

#define	GUIID_RELOADCONFIGURATIONLIST       (GUIID_DEFAULT+32)

#define	GUIID_EVENT_TWITTERSHARETOTALGAMESCORE         (GUIID_DEFAULT+33)
#define	GUIID_EVENT_FACEBOOKSHARETOTALGAMESCORE         (GUIID_DEFAULT+34)

#define	GUIID_EVENT_OPENHELPVIEW         (GUIID_DEFAULT+35)

#define	GUIID_EVENT_OPENONLINEGAMERSTATUSVIEW         (GUIID_DEFAULT+36)
#define	GUIID_EVENT_ONLINESTATUSBUTTON                  (GUIID_DEFAULT+37)
