/*
 *  ApplicationResource.h
 *  ChuiNiuLite
 *
 *  Created by Zhaohui Xing on 11-03-04.
 *  Copyright 2011 __MyCompanyName__. All rights reserved.
 *
 */
#import "ApplicationConfigure.h"
#import "GUIBasicConstant.h"

#define	 PRODUCTID_DEFAULT					APPLICATION_PRODUCT_FLYINGCOW		


#define	 GUIID_DEFAULT						GUIID_BASIC_IDLAST
#define	 GUIID_INFOBUTTON					(GUIID_DEFAULT+1)
#define	 GUIID_PLAYBUTTON					(GUIID_DEFAULT+2)
#define	 GUIID_UNDOBUTTON					(GUIID_DEFAULT+3)
#define	 GUIID_CONFIGUREBUTTON				(GUIID_DEFAULT+4)
#define	 GUIID_BKGNDBUTTON					(GUIID_DEFAULT+5)
#define	 GUIID_POINTSBUTTON					(GUIID_DEFAULT+6)
#define	 GUIID_SCOREBUTTON					(GUIID_DEFAULT+7)
#define	 GUIID_POSTBUTTON					(GUIID_DEFAULT+8)

#define	 GUIID_EVENT_OPENCONFIGUREVIEW		(GUIID_DEFAULT+9)
#define	 GUIID_EVENT_OPENSCOREVIEW			(GUIID_DEFAULT+10)
#define	 GUIID_EVENT_OPENSHAREVIEW			(GUIID_DEFAULT+11)
#define	 GUIID_EVENT_GOTONEWGAMEBUTTON		(GUIID_DEFAULT+12)
#define	 GUIID_EVENT_FACEBOOKSHARELAST		(GUIID_DEFAULT+13)
#define	 GUIID_EVENT_FACEBOOKSHAREALL		(GUIID_DEFAULT+14)
#define	 GUIID_EVENT_RENRENSHARELAST        (GUIID_DEFAULT+15)
#define	 GUIID_EVENT_RENRENSHAREALL         (GUIID_DEFAULT+16)
#define	 GUIID_EVENT_QQSHARELAST            (GUIID_DEFAULT+17)
#define	 GUIID_EVENT_QQSHAREALL             (GUIID_DEFAULT+18)
#define	 GUIID_EVENT_SINASHARELAST          (GUIID_DEFAULT+19)
#define	 GUIID_EVENT_SINASHAREALL           (GUIID_DEFAULT+20)
#define	 GUIID_EVENT_QQLOGINFAILED          (GUIID_DEFAULT+21)
#define	 GUIID_EVENT_QQLOGINSUCCEED         (GUIID_DEFAULT+22)
#define	 GUIID_EVENT_POINTSCHANGED          (GUIID_DEFAULT+23)

#define	 GUIID_PURCHASEBUTTON				(GUIID_DEFAULT+24)
#define	 GUIID_EVENT_PURCHASE				(GUIID_DEFAULT+25)
#define	 GUIID_EVENT_TRIANGLEICONCLICK		(GUIID_DEFAULT+26)
#define	 GUIID_EVENT_SQUAREICONCLICK		(GUIID_DEFAULT+27)
#define	 GUIID_EVENT_DIAMONDICONCLICK		(GUIID_DEFAULT+28)
#define	 GUIID_EVENT_HEXGONICONCLICK		(GUIID_DEFAULT+29)
#define	 GUIID_EVENT_MATRIXICONCLICK		(GUIID_DEFAULT+30)
#define	 GUIID_EVENT_SNAKEICONCLICK         (GUIID_DEFAULT+31)
#define	 GUIID_EVENT_SPIRALICONCLICK		(GUIID_DEFAULT+32)
#define	 GUIID_EVENT_CONFIGURECHANGE		(GUIID_DEFAULT+33)
#define	 GUIID_EVENT_PLAYSTEPCHANGE         (GUIID_DEFAULT+34)
#define	 GUIID_EVENT_WIZARDFINISHED         (GUIID_DEFAULT+35)
#define	 GUIID_EVENT_DISABLEICONVIEWCLICK   (GUIID_DEFAULT+36)

#define	 GUIID_EVENT_COLORBUBBLEICONCLICK		(GUIID_DEFAULT+37)
#define	 GUIID_EVENT_STARBUBBLEICONCLICK        (GUIID_DEFAULT+38)
#define	 GUIID_EVENT_WOODBUBBLEICONCLICK		(GUIID_DEFAULT+39)

#define	 GUIID_FRIENDBUTTON					(GUIID_DEFAULT+40)
#define	 GUIID_OPENFRIENDVIEW				(GUIID_DEFAULT+41)

#define	 GUIID_EVENT_TWITTERSHARELAST       (GUIID_DEFAULT+42)
#define	 GUIID_EVENT_OPENFILESAVEUI         (GUIID_DEFAULT+43)
#define	 GUIID_EVENT_FILELISTUICLOSED       (GUIID_DEFAULT+44)
#define	 GUIID_EVENT_FILELISTPREVIEWCLICK   (GUIID_DEFAULT+45)
#define	 GUIID_EVENT_OPENPLAYHELPVIEW       (GUIID_DEFAULT+46)
#define	 GUIID_EVENT_RESETEASYGAMESHUFFLE   (GUIID_DEFAULT+47)
#define	 GUIID_EVENT_GAMEWINNOTIFICATION    (GUIID_DEFAULT+48)
#define	 GUIID_EVENT_GOTONEXTGAMENOTIFICATION    (GUIID_DEFAULT+49)

#define	 GUIID_EVENT_BLUEBUBBLEICONCLICK		(GUIID_DEFAULT+50)
#define	 GUIID_EVENT_REDHEARTBUBBLEICONCLICK        (GUIID_DEFAULT+51)

#define  GUIID_SCOREHELPVIEWBUTTON                  (GUIID_DEFAULT+52)

#define  GUIID_EVENT_OPENSCOREHELPVIEW                 (GUIID_DEFAULT+53)

#define  GUIID_EVENT_ONLINESTATUSBUTTON             (GUIID_DEFAULT+54)

#define  GUIID_EVENT_POSTONLINESCORE             (GUIID_DEFAULT+55)


#define FILEUI_CANCEL                   0
#define FILEUI_OK                       1
#define FILEUI_FILENAME                 2
#define FILEUI_CREATORNAME              3
#define FILEUI_CREATOREMAIL             4
#define FILEUI_GAMEPREVIEW              5
#define FILEUI_CREATORLOCATION          6
#define FILEUI_CREATORDEVICE            7
#define FILEUI_CREATORAPPVERSION        8
#define FILEUI_MYLASTPLAYLOCATION       9
#define FILEUI_MYLASTPLAYNAME           10
#define FILEUI_SHARE                    11
#define FILEUI_MYLASTPLAYEMAIL          12

#define FILEUI_LASTFIXEDID              FILEUI_MYLASTPLAYEMAIL+1

